export { MEMBERS };

const MEMBERS = [
    {icon: 'icon1',
    name: ['hollywood787', 'hollywood7878@yandex.ru'],
    color: 'rgb(101, 189, 243)',
    },
    {icon: 'icon2',
    name: ['соня', '@maksimka_priroda', 'pipupopi', "sonalavrushina@gmail.com"],
    color: 'rgb(180, 139, 242)',
    },
    {icon: 'icon3',
    name: ['Daria Ovsiannykova 🌱', 'dariannyko@gmail.com', '@dariannyko', 'Dariannyko'],
    color: 'rgb(180, 139, 242)', 
    },
    {icon: 'icon4',
    name: ['ᅠ'],
    color: 'rgb(191, 81, 91)',
    },
    {icon: 'icon5',
    name: ['Yaroslav Shishkin',],
    color: 'rgb(98, 212, 227)', 
    },
    {icon: 'icon6',
    name: ['Banan 🍌 Baldja',],
    color: 'rgb(180, 139, 242)', 
    },
    {icon: 'icon7',
    name: ['Artem Dimitrov', '@artdimitrov', 'art@strada.one'],
    color: 'rgb(133, 222, 133)', 
    },
    {icon: 'icon8',
    name: ['yarolly', 'Kate', 'Ya Rolly 🔱', '@YaRolly'],
    color: 'rgb(180, 139, 242)', 
    },
    {icon: 'icon9',
    name: ['Vitalik', '@meVarensev', 'meVarensev', 'Varensev Vitaliy'],
    color: 'rgb(255, 140, 0)', 
    },
    {icon: 'icon10',
    name: ['Михаил', '@st_Miguel_st',],
    color: 'rgb(101, 189, 243)', 
    },
    {icon: 'icon11',
    name: ['Michael Korolev', '@koro1ev',],
    color: 'rgb(133, 222, 133)',
    },
    {icon: 'icon12',
    name: ['Alex Rusakov', '@AlexeyRusakov1999',],
    color: 'rgb(98, 212, 227)',
    },
    {icon: 'icon13',
    name: ['Kseniya',],
    color: 'rgb(133, 222, 133)',
    },
    {icon: 'icon14',
    name: ['Timofey Tarasov', 'timofiei.tarasov@gmail.com',],
    color: 'rgb(255, 86, 148)',
    },
    {icon: 'icon15',
    name: ['боря китаев', '@etonikomunenujno',],
    color: 'rgb(98, 212, 227)', 
    },
    {icon: 'icon16',
    name: ['Павел Строгов', '@strogovpv',],
    color: 'rgb(255, 140, 0)', 
    },
    {icon: 'icon17',
    name: ['Egor Sychev', '@xvoddd',],
    color: 'rgb(133, 222, 133)', 
    }, 
    {icon: 'icon18',
    name: ['kate', 'kamkinaz64@gmail.com',],
    color: 'rgb(255, 140, 0)',  
    },
    {icon: 'icon19',
    name: ['илназ', 'ilnazrt@mail.ru', "ilnazrt@mail.ru", '237x237@gmail.com'],
    color: 'rgb(255, 140, 0)',  
    },
    {icon: 'icon20',
    name: ["hunky@list.ru", "hamit.magic@gmail.com"],
    color: 'rgb(255, 140, 0)', 
    },
    {icon: 'icon21',
    name: ['Ethernal', 'tighineanu00@mail.ru'],
    color: 'rgb(180, 139, 242)', 
    },
];


