export const ELEMENTS = {
    SETTINGS_WRAPPER: document.querySelector('.settings_wrapper'),
    MAIN_BLOCK: document.querySelector('.main-block'),
    BUTTON_SETTINGS: document.querySelector('.btn-settings'),
    BUTTON_CLOSE_SETTINGS: document.querySelector('#settings-btn'),
    MESSAGE_FORM: document.querySelector('.message_form'),
    MESSAGE_INPUT: document.querySelector('.my_message-input'), 
    MY_MESSAGES: document.querySelector('.message-window'),
    MY_MESSAGE_TEMPLATE: document.querySelector('#template_my_message'), 
    AUTHORIZATION_WRAPPER: document.querySelector('.authorization_wrapper'),
    BUTTON_EXIT: document.querySelector('.btn-exit'),
    BUTTON_GET_CODE: document.querySelector('#btn-authorization'),
    CONFIRMATION_WRAPPER: document.querySelector('.confirmation_wrapper'),
    // POPUP_INPUTS: document.querySelector('.name_input'),
    BUTTON_CLOSE_AUTHORIZATION: document.querySelector('#authorization-btn'),
    BUTTON_CLOSE_CONFIRMATION: document.querySelector('#confirmation-btn'),
    AUTHORIZATION_FORM: document.querySelector('.authorization-form'),
    INPUT_MAIL: document.querySelector('#input-for-mail'),
};