export const ELEMENTS = {
  DEGREES_NUMBER: document.querySelector(".degrees"),
  NEW_TEMP: document.createElement("p"),
  CITY_NAME: document.querySelector(".forecast-months"),
  NEW_NAME_CITY: document.createElement("p"),
  HEART: document.querySelector(".heart"),
  SAVE_CITY_FORM: document.querySelector(".locations-items"),
  DETAILS_CITY: document.querySelector(".text-locations"),
  DETAILS_TEMP: document.querySelector(".temp"),
  DETAILS_FEEL_LIKE: document.querySelector(".feel-like"),
  DETAILS_WEATHER: document.querySelector(".weatherLi"),
  DETAILS_SUNRISE: document.querySelector(".sunrise"),
  DETAILS_SUNSET: document.querySelector(".sunset"),
  FORECAST_CITY: document.getElementById('forecast-name'),
  FORECAST_DATE_TODAY1: document.getElementById('date-today1'),
  FORECAST_DATE_TODAY2: document.getElementById('date-today2'),
  FORECAST_DATE_TODAY3: document.getElementById('date-today3'),
  FORECAST_TEMP_12_HOUR: document.querySelector('.temp-12hour'),
  FORECAST_FEEL_12_HOUR: document.querySelector('.feels-12hour'),
  FORECAST_WEATHER_12_HOUR: document.querySelector('.weather-12hour'),
  FORECAST_ICON_12_HOUR: document.querySelector('.forecast-icon12h'),
  FORECAST_TEMP_15_HOUR: document.querySelector('.temp-15hour'),
  FORECAST_FEEL_15_HOUR: document.querySelector('.feels-15hour'),
  FORECAST_WEATHER_15_HOUR: document.querySelector('.weather-15hour'),
  FORECAST_ICON_15_HOUR: document.querySelector('.forecast-icon15h'),
  FORECAST_TEMP_18_HOUR: document.querySelector('.temp-18hour'),
  FORECAST_FEEL_18_HOUR: document.querySelector('.feels-18hour'),
  FORECAST_WEATHER_18_HOUR: document.querySelector('.weather-18hour'),
  FORECAST_ICON_18_HOUR: document.querySelector('.forecast-icon18h'),
};

