export const ELEMENTS = {
  SETTINGS_WRAPPER: document.querySelector('.settings_wrapper'),
  BTN_SETTINGS: document.querySelector('.btn-settings'),
  CLOSE_WINDOW: document.querySelector('.close-window'),
  MAIN_BLOCK: document.querySelector('.main-block'),
  FORM: document.querySelector('form'),
  MY_MESSAGE_INPUT: document.querySelector('.my_message-input'),
  TEMPLATE_MY_MESSAGE: document.getElementById('template_my_message'),
  TEMPLATE_OTHER_MESSAGE: document.getElementById('template_other_message'),
  MESSAGE_WINDOW: document.querySelector('.message-window'),
  CLOSE_BTNS: document.querySelectorAll('.close-window'),
  AUTHORIZATION: document.querySelector('.sign-in_wrapper'),
  POPUP_SETTINGS: document.querySelector('.block-settings'),
  MAIL_INPUT: document.querySelector('.mail_input'),
  BTN_MAIL_SEND: document.querySelector('.btn_mail_send'),
  CODE_INPUT: document.querySelector('.code_input'),
  BTN_CODE_SEND: document.querySelector('.btn_code_send'),
  CODE_WINDOW: document.querySelector('.settings_wrapper.code_window'),
  URL: 'https://edu.strada.one/api/user',
  OTHER_MESSAGE: document.querySelector('.message_other'),
  NAME_OTHER: document.querySelector('.name_other'),
  OTHER_MESSAGE_WRAPPER: document.querySelector('.other_message-block'),
  BTN_NAME_CHAT: document.querySelector('.btn_name_in_chat'),
  NAME_IN_CHAT: document.querySelector('.name_input'),
  MESSAGES_CLEAR: document.querySelector('.message_clear'),
  WINDOW_SCROLL: document.querySelector('.message-window'),
};
